### ISSUE TITLE
How to use your code?

### ISSUE THREAD

**Issue by MindAI** [guma44/ushuffle#1]
The Usage in REAMDE does not work. 

While I appreciate your effort in putting your code on Github, but if it's not well commented, nobody is ever able to use it.

**Comment by guma44** [comment]
Hi, thanks for the report. The new version is there. I hope that satisfy your need. In the future I would appreciate more information on what you would try to do, what operating system, what python version etc.

BTW. The beauty of GitHub is that you also could check it, fix it and make a pull request :).
