### ISSUE TITLE
ImportError: No module named 'Cython'

### ISSUE THREAD

**Issue by Jessime** [guma44/ushuffle#2]
If I try to install ushuffle in a clean environment, I get:

```
jessime:~/workspace $ pip3 install ushuffle
Downloading/unpacking ushuffle
  Downloading ushuffle-1.0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_ubuntu/ushuffle/setup.py) egg_info for package ushuffle
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_ubuntu/ushuffle/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_ubuntu/ushuffle/setup.py", line 2, in <module>

    from Cython.Build import cythonize

ImportError: No module named 'Cython'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_ubuntu/ushuffle
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

Normally, this is fine for me, since I can just manually install `cython`, then repeat the `pip install ushuffle`. But, I'm trying to make ushuffle a dependency of a package I'm writing, and don't want to have to tell people to do a two step install. There's some discussion about it here:

https://stackoverflow.com/questions/44554882/in-a-setup-py-involving-cython-if-install-requires-then-how-can-from-library-i

I'm looking into solutions, but do you have any thoughts on how to fix this?

**Comment by guma44** [comment]
Hi, This is a good point. I think I will go with the solution that pandas provide.

**Comment by Jessime** [comment]
Hey, thanks for the quick reply! Is there anything I can do to help with this?

I'd love to add `ushuffle` to my package, but am also on a fairly tight deadline for pulling things together (on the order of a few weeks). So if there's anything I can contribute, let me know!

**Comment by guma44** [comment]
I will try to fix it.

**Comment by guma44** [comment]
I released new version in which the problem should be solved. Let me know if this is what you need.

**Comment by Jessime** [comment]
Wow, that was super fast, thanks! I'm running py3 though, so I crash out on the print statement:

```
Collecting ushuffle
  Downloading https://files.pythonhosted.org/packages/a3/30/2ac23ddf1b6e92f33741f8b595958b07ca85b39a5e28545dca5b5d3000d0/ushuffle-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rltx_xew/ushuffle/setup.py", line 9
        print "No Cython installed. Building from pre-compiled sources."
                                                                       ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No Cython installed. Building from pre-compiled sources.")?
```

I don't know if you have explicit support for py3, but it's been fine in the past.

**Comment by guma44** [comment]
My bad :smile:. I already pushed the corrected version. Should not have make this.

**Comment by guma44** [comment]
So, I tried few things about this issue. It turned out that the solution was easy. The s(dist) will not provide the file to the tarball until it is explicitly said so in the Manifest file. It took me few iteration to realize that :D. I hope now  the problem is solved so I could close the issue.

**Comment by Jessime** [comment]
```
$ pip install ushuffle --no-cache-dir

Collecting ushuffle
  Downloading https://files.pythonhosted.org/packages/3e/12/79d8dc4b39594246bbf2cf4bb69ac6dc6f9e57ebbc099492375415d8078e/ushuffle-1.0.9.tar.gz
Installing collected packages: ushuffle
  Running setup.py install for ushuffle ... done
Successfully installed ushuffle-1.0.9
```

This is beautiful, thank you! Going to go ahead and close.
