### ISSUE TITLE
Using a seed

### ISSUE THREAD

**Issue by Jessime** [guma44/ushuffle#3]
I may just be missing something, but is there any way to set a seed to `ushuffle` in Python? I see that `ushuffle/src/main.c` uses a seed, but nothing else does. It would be great to be able to reproduce results between runs!

**Comment by guma44** [comment]
So now you can use globally a function `set_seed`. However, before the seed was always set to anyway to 1 (as it is a default value) and the subsequent runs were reproducible. Thus, there is no need to use it.
