### ISSUE TITLE
Python 3 compatible?

### ISSUE THREAD

**Issue by michauhl** [guma44/ushuffle#5]
Hello, 
I wonder whether the library also work with Python 3?
I installed it with:
`pip install ushuffle`
Under Python 2.7 the example code works fine. Under Python 3 (3.7.3) I get the error:
`
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    shuffler = Shuffler(seq, 2)
  File "ushuffle.pyx", line 27, in ushuffle.Shuffler.__cinit__
`
Is there some easy way to fix this? Or any future updates that will make it compatible?
Thanks & Best,
Michael

**Comment by guma44** [comment]
Hi,
Tanks for sharing. In principle library is compatible. I will look at this issue.
Rafal

**Comment by guma44** [comment]
So I check in fresh venv (Python 3.6.4) and it is working. Here is an example (as the default is for python 2):
```python
from ushuffle import shuffle, Shuffler
seq = b"ababcdcdabdcabvababab"
shuffler = Shuffler(seq, 2)
for i in range(10):
    seqres = shuffler.shuffle()
    print("results:", seqres)
print(shuffle(seq, 2))
```

**Comment by michauhl** [comment]
Hi Rafal, 

thanks for the quick response! It's working now here too, weird (Python 3.7.3). If I can reproduce the error, I will let you know :)

All the best,
Michael

**Comment by michauhl** [comment]
I just saw, it was because of the byte object to string thingy. The example code above works fine for Python 3, while the one in the README works fine for Python 2.

**Comment by guma44** [comment]
Good, I think I will update docs for this.
